---
title: "Demo 360 Quarto analysis"
subtitle: "With another comment on the thing here"
author: "James Goldie, 360info"
date: "2022-03-11"
code-fold: true
theme: style/article.scss
---

```{r}
library(tidyverse)
library(lubridate)
library(themes360info)
library(here)
```

```{r}
here("data", "deathrow.csv") %>%
  read_csv() %>%
  filter(country != "Vietnam") %>%
  mutate(
    date = ymd(paste0(year, "-07-01")),
    deathrow_all = deathrow_drugs_ppl / deathrow_drugs_frac) %>%
  pivot_longer(c(deathrow_drugs_ppl, deathrow_all),
    names_to = "measure", values_to = "count") %>%
  mutate(measure = recode(measure,
    "deathrow_drugs_ppl" = "Drug offences",
    "deathrow_all" = "Any offence")) %>%
  {
    ggplot(.) +
      aes(x = year, y = count, colour = measure) +
      geom_point() +
      geom_line() +
      scale_colour_manual(
        values = c("Drug offences" = "red", "Any offence" = "black"),
        name = "Offence") +
      facet_wrap(vars(country), scales = "free_y") +
      theme_360() +
      theme(
        legend.position = "top",
        legend.direction = "horizontal")
  }
```